### ISSUE TITLE
Zoosystema: font issues z2017n1a3_0

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#370] opened 2017-12-03 15:12 UTC
same file as in https://github.com/gsautter/goldengate-imagine/files/1524872/z2017n1a3_0.pdf

run as default
![image](https://user-images.githubusercontent.com/4609956/33526660-b7707ade-d844-11e7-9b90-a79a8e09c901.png)

**Comment by myrmoteras** [comment] 2017-12-03 15:18
run as glyph
![image](https://user-images.githubusercontent.com/4609956/33526723-9567790a-d845-11e7-89fa-f02568a5295b.png)

can't fix the fonts using "edit fonts"

**Comment by myrmoteras** [comment] 2017-12-03 15:22
basic latin

![image](https://user-images.githubusercontent.com/4609956/33526767-1bbe4678-d846-11e7-8061-bbae5e11d6f0.png)

**Comment by myrmoteras** [comment] 2017-12-03 15:27
extended latin

![image](https://user-images.githubusercontent.com/4609956/33526827-df688408-d846-11e7-9287-a035177354dc.png)

**Comment by gsautter** [comment] 2017-12-04 01:20
A duplicate of #369 in terms of word width overruns, but also a glyph decoding issue.

Regarding the latter, have you tried the "Latin" decoding option?

**Comment by myrmoteras** [comment] 2017-12-04 08:27
see above yes.

the closest I get is using "do not decode), but the font errors cannot be changed

![image](https://user-images.githubusercontent.com/4609956/33542910-411fc2a4-d8d5-11e7-87f2-b9033f0b6ff9.png)

**Comment by gsautter** [comment] 2017-12-04 19:30
Thanks for trying this out and testing through the options.

It might well be the case that this is one of the fonts that are subject to the latest bugfix in the glyph renderer, which is not online just yet.

I'll see if I have any energy left to make a new build after going through today's tickets ...

**Comment by gsautter** [comment] 2017-12-04 19:42
I decoded this one last night on the train with "Render Gylphs Only", and it's looking pretty good in the GGI font editor.

What do the glyphs look like in your IMF decoded with the same option? If they are garbled, see my last post above.

I have to state, though, that especially the italics fonts in this one are pretty artsy, and thus some bunch of glyphs might actually end up failing to match with their Liberation Font standard counterparts, which the font decoder uses for comparison.

**Comment by gsautter** [comment] 2017-12-04 19:46
What's more, this PDF uses an excessive number of obviously identical fonts (all derived from the same base font) throughout the pages, which I am not so sure right now doesn't get in the way of decoding.

Actually, derived fonts are my prime suspect right now for the word width overruns and the resulting obstruction of column gaps. I might get around to investigating in this direction a bit after working off today's tickets.

**Comment by gsautter** [comment] 2017-12-08 23:15
The word width overruns were actually word spacing overruns (see #369) and are fixed now. See the latter for an explanation of the underlying problem.

**Comment by gsautter** [comment] 2017-12-08 23:15
The font rendering issues I cannot reproduce any more, so they should be fixed with the next build.

**Closed by gsautter** 2017-12-08 23:15 UTC
