### ISSUE TITLE
table: header not detected zootaxa.4660.1.1

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#736] opened 2019-08-26 08:13 UTC
![image](https://user-images.githubusercontent.com/4609956/63675881-1596f480-c7ea-11e9-8002-2cd3c7537b31.png)

**Comment by gsautter** [comment] 2019-08-26 16:39
I see ... anyway, this is a duplicate of #734 .

**Closed by gsautter** 2019-08-26 16:39 UTC

**Comment by gsautter** [comment] 2019-08-26 17:58
Sorry, not quite a duplicate, but related ... apparently, with all the intermediate grid lines, these somewhat serrated multi-row headers get scored out of the table, as the table body alone is more regular and thus scores higher ... hard one.

The headers then become a table note for being stuck between the table and its caption, which is a layout that does occur at times. Wrong behavior here, but only a downstream effect of the above.
