### ISSUE TITLE
upload error: java heap space

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#252] opened 2017-09-13 12:28 UTC
this is a huge IMF file 604MB. It always, repeatedly stops, always at figure@46
see a similar case at https://github.com/plazi/EJT-testbed/issues/79

the link to the IMF file is here  https://drive.google.com/file/d/0B3vUTWty5VsocEFQVE9qWHVHZjg/view 
![image](https://user-images.githubusercontent.com/4609956/30377276-74b011a4-988f-11e7-996a-6970049695e7.png)

**Comment by myrmoteras** [comment] 2017-09-13 12:33
[GgImagine.20170913-1349.err.zip](https://github.com/gsautter/goldengate-imagine/files/1299397/GgImagine.20170913-1349.err.zip)

**Comment by gsautter** [comment] 2017-09-13 22:48
Please try the following:
- open the IMF
- save to an "Image Markup Directory"
- close GGI
- re-open GGI
- load the document from the IMD (Image Markup Directory)
- re-attempt the upload

Background: An IMF is zipped, so on opening the first thing to happen is un-zipping it, keeping all the extracted content in memory. An IMD basically is an un-zipped IMF in a dedicated folder. When opening an IMD, there is no un-zipped content to be kept in memory, as all the entries are loaded on demand right from disk. This should give you enough room for the upload to succeed.

**Comment by myrmoteras** [comment] 2017-09-18 06:22
this does not work. A new attempt with zt02456p243
[zt02456p243.pdf](https://github.com/gsautter/goldengate-imagine/files/1309833/zt02456p243.pdf) this files turns out to become from a 8MB a 256 MB file!
It also does not work in the batch, becuase it is a Monograph where the meta data is not extrated properly
E:\diglib\zootaxa\2010\pdf_2010_notProcessed

**Comment by gsautter** [comment] 2017-09-18 18:29
Factor 32 increase ... that's outrageous. Will check.

**Comment by gsautter** [comment] 2017-09-18 18:29
Working hypothesis: Some ultra-high resolution line drawing(s).

**Comment by gsautter** [comment] 2017-09-18 18:58
OK, completely wrong, wasn't any high resolution figures or drawing ... just the sheer number of pages, page images, and figures. neither of the latter is even remotely excessive in size (all between 1 and 3 MB), it's just that they are so many.

**Comment by gsautter** [comment] 2017-09-18 19:00
The actual reason for the factor 32 increase in size is that there are many comparatively low resolution figures, which make the page images row in volume.

**Comment by gsautter** [comment] 2017-09-18 19:18
Anyway, the IMF uploaded just smoothly on the very first attempt, UUID is D720FFDA046FFFFDFFF5B267FFDCFF98 . If you don't find the file right away, wait a little, as the batch has taken over soon as I released the IMF.

Not sure what's happening on your machine ... RAM consumption wasn't all that high throughout the upload (some 1.5 GB). How much disk space do you have free on the drive GGI is _installed_ on?

**Comment by myrmoteras** [comment] 2017-09-18 21:12
23GB free

**Comment by gsautter** [comment] 2017-09-18 21:50
This is getting more and more weird ... especially in conjunction with the font issues you keep reporting that I can barely ever seem to reproduce.

I really want to run some tests on your machine next time we have the opportunity.

**Comment by gsautter** [comment] 2017-09-19 18:49
Please let's stick with _one_ ticket per issue ... closing this one as a duplicate of #257.

**Closed by gsautter** 2017-09-19 18:49 UTC
