### ISSUE TITLE
duplicate entries in BLR: bug

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#136] opened 2017-04-03 09:19 UTC
When entering a document to BLR via GGI without the original DOI in the doc metdata, a new DOI for the article is created.

When correcting the metadata and entering the original DOI, a new record in BLR is created, including all the images, which included the source DOI.

Example: 
![image](https://cloud.githubusercontent.com/assets/4609956/24602922/289cbc14-185f-11e7-9814-c5b13063b860.png)
deposition with correct DOI
https://zenodo.org/record/439843
https://zenodo.org/record/439842

old deposition
https://zenodo.org/record/439839
https://zenodo.org/record/439838

**Comment by gsautter** [comment] 2017-04-03 20:06
Figure 3 (the line drawing) comes in 3000 (!!!) DPI, basically killing off the server in an attempt to render it. I'll try and scale it down in some kind of way, but it might be hard.

**Comment by gsautter** [comment] 2017-04-03 20:07
on top, this is basically a duplicate of #141, as the latter is the underlying cause of the problem.

**Closed by gsautter** 2017-04-03 20:07 UTC
