### ISSUE TITLE
bibRef not marked up: zootaxa.4379.2.3

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#430] opened 2018-02-14 22:15 UTC
[zootaxa.4379.2.3.pdf](https://github.com/gsautter/goldengate-imagine/files/1725828/zootaxa.4379.2.3.pdf)

In this zootaxa, using your new FM=U and the latest built in the batch mode, all the bibRefs are not marked up.

The same for most of the bibRefs in zootaxa.4379.2.1, but which is too big to add here

**Comment by gsautter** [comment] 2018-02-15 00:04
The copy&paste test tells me the Unicode mapping of the fonts is just fine ... will investigate the reference tagging part.

**Comment by gsautter** [comment] 2018-02-15 00:38
A pretty pathological problem is that paragraph break analysis fails to recognize "Martens, J. (1978) Spinnentiere, Arachnida: Weberknechte, Opiliones. In: Senglaub, K., Hannenmann, H.J. & Schumann, H. (Eds.), Die Tierwelt Deutschlands, Vol. 64. Gustav Fischer Verlag, Jena, pp. 1–464" as a single paragraph, breaking bibliographic reference detection right there. The pathological part is the page break right after "... Schumann, H." (mind the terminal dot), which makes it close to impossible to tell (on the syntactical level, and that's all that paragraph continuation analysis has) that the paragraph continues with "(Eds.) ..."
This failed paragraph continuation pretty much breaks the bibliography in the middle.

**Comment by gsautter** [comment] 2018-02-15 00:48
Running bibliographic reference tagging in XML view with normalized characters further reveals that reference tagging proper doesn't seem to be the problem here at all, as all of the bibliography tags just fine, including separate paragraph URLs and DOIs.

On to of document structure detection failing to identify and connect the aforementioned two paragraphs as a single one crossing a page break, character normalization appears to be an issue, and I'll investigate in that direction.

The new bibliographic reference tagger proper works just like supposed to.

**Comment by gsautter** [comment] 2018-02-15 00:59
After a respective test, character normalization issues are acquitted ... it's merely the wrongful cross page paragraph break that seems to derail the reference tagger. I'll try and figure out a way of properly detecting such cross-page paragraph continuations, maybe based on indentation.

**Comment by myrmoteras** [comment] 2018-02-16 12:02
sorrry, added more here https://github.com/plazi/Plazi-Communications/issues/759

**Comment by gsautter** [comment] 2018-02-16 14:16
https://github.com/plazi/Plazi-Communications/issues/759 is about character normalization, which is completely orthogonal to the paragraph break problem in this very ticket. All the two have in common is them getting in the way of bibliographic reference detection. And solutions will be quite distinct as well.

**Comment by gsautter** [comment] 2018-02-16 20:14
This has nothing to do with diacritics, not at all, as the whole bibliographic reference processing (tagging and parsing) works with normalized text.
The problem are mostly (a) broken sort order, see https://github.com/plazi/Plazi-Communications/issues/759 and (b) cross-page paragraphs happening to split at points that make them extremely hard to identify as one.

(a) is solved now, see https://github.com/plazi/Plazi-Communications/issues/759
(b) is something I'll take care in due time, namely by factoring in text block level paragraph layout assessment when determining whether or not the first paragraph in a block is actually a continuation from the preceding page or column.

**Comment by myrmoteras** [comment] 2018-02-16 20:59
here the results of those Zootaxa processed today which had a problem with the bibRefs. See also https://docs.google.com/spreadsheets/d/1q-VskOXT87Qt_Mj1MNjGFZOdCKq4UDDQgxTe6WXaxDs/edit#gid=0

zootaxa.4379.3.2
not marked up to close to the end

![image](https://user-images.githubusercontent.com/4609956/36328985-855993ea-1364-11e8-8341-eb7943431607.png)

![image](https://user-images.githubusercontent.com/4609956/36328989-8b92c3b2-1364-11e8-8420-1f951691f1f3.png)

**Comment by myrmoteras** [comment] 2018-02-16 21:00
zootaxa.4379.3.3

![image](https://user-images.githubusercontent.com/4609956/36329018-aa231dae-1364-11e8-863b-e14c159c824e.png)

Might have something to do with the missing author markup 
![image](https://user-images.githubusercontent.com/4609956/36329036-bdb3c260-1364-11e8-9982-4ee7a9a86971.png)

**Comment by myrmoteras** [comment] 2018-02-17 16:31
zootaxa.4379.3.11

![image](https://user-images.githubusercontent.com/4609956/36343122-59aac0da-1408-11e8-9475-49f64c6e3e9a.png)

**Comment by myrmoteras** [comment] 2018-02-17 17:04
zootaxa.4379.4.2
![image](https://user-images.githubusercontent.com/4609956/36343472-00f4f58c-140d-11e8-9fe5-a48ad81ecb2b.png)

**Comment by gsautter** [comment] 2018-02-17 19:19
Again, this is about sort order ... why is "Swierczewski, D. (2018)" before "Swierczewski, D. (2013)"? However, the tolerance for slight inconsistencies in sort order that I integrated yesterday should save this. Just not out yet.

**Comment by gsautter** [comment] 2018-02-17 19:22
"wilkinson, J.A.", on the other hand, most likely fails to tag at all. And looking at the lower case W, I'm not amazed at all it does. This could be either of  font decoding error or a typo in the original document. Considering the complete absence of other font problems, as well as the presence of a lower case W in "Drewes", I'd fancy the typo. Little we could do about this.

**Comment by myrmoteras** [comment] 2018-02-20 12:39
zootaxa.4382.1.2
after Linder, all the bibRefs are missing

![image](https://user-images.githubusercontent.com/4609956/36424381-62f61c60-1643-11e8-8d25-6a99809bef09.png)

**Comment by gsautter** [comment] 2018-05-11 19:51
I just ran 4382.1.2 with the same setup as in #462 (decode PDF, detect document structure, parse bibliography), and it came up perfectly fine. Really baffled ...

**Comment by gsautter** [comment] 2018-05-11 19:53
Closing this one now as a duplicate of the more recent #462 ... but could not reproduce anything in the PDFs mentioned over there, either.

**Closed by gsautter** 2018-05-11 19:53 UTC
