### ISSUE TITLE
bibRef not discovered

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#334] opened 2017-11-02 16:07 UTC
in this case, the bibRef have not been discovered

![image](https://user-images.githubusercontent.com/4609956/32335134-77ec0dd0-bfec-11e7-9942-39b0ce12212a.png)
[6_Hollier_Wesener.pdf](https://github.com/gsautter/goldengate-imagine/files/1438367/6_Hollier_Wesener.pdf)

**Comment by gsautter** [comment] 2017-11-02 17:03
This is a duplicate of #326 , only with "de" getting in the way instead of "van".

**Closed by gsautter** 2017-11-02 17:03 UTC
