### ISSUE TITLE
pdf not processed: zootaxa.4299.4.8

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#187] opened 2017-08-09 04:54 UTC
[zootaxa.4299.4.8.pdf](https://github.com/gsautter/goldengate-imagine/files/1210363/zootaxa.4299.4.8.pdf)

Processing document 'D:\diglib\zootaxa\2017\temp\zootaxa.4299.4.8.pdf'
 - loaded PDF of 4263317 bytes
Extracting page content
Assessing font char usage
Importing page words
Sanitizing page words and graphics
Handling flipped page content
Analyzing words in relation to figures and graphics
Storing custom fonts
Assessing number punctuation
Splitting page words
Generating page images
Generating pages
Analyzing page structure
Analyzing text stream structure
 - PDF converted, document ID is 'FFB65D5EFFEE7D258908FFF60501E67A'
 - assigned document style 'zootaxa.2013.journal_article'
Running Image Markup Tool 'Detect Document Structure'
Detecting document structure from 11 pages
 - gathering data
 - scoring page numbers:
 - checking page number sequence:
 - filling in missing page numbers:
 - detecting page headers
 - correcting empty tables
 - detecting tables
 - computing main text font size
 - detecting captions
 - detecting footnotes
 - indexing paragraph end words
 - de-hyphenating line breaks
 - merging interrupted paragraphs
 - identifying caption target areas
 - merging tables within pages
 - merging tables across pages
 - marking caption citations
 - marking headings and emphases
Running Image Markup Tool 'Add Document Meta Data'
Running Image Markup Tool 'Mark Taxonomic Keys'
Running Image Markup Tool 'Parse Bibliography'
Wrapping document
Checking document
Loading document processor
Running Image Markup Tool 'Mark Bibliographic Citations'
Wrapping document
Checking document
Loading document processor
Processing document
Running Image Markup Tool 'Mark Taxon Names'
Wrapping document
Checking document
Loading document processor
Collecting seed families and genera
Collecting above-genus seeds
Eliminating seeds from document head and bibliography
Eliminating stop words
Eliminating seeds with inappropriate suffixes
Eliminating document local stop words
Eliminating non-emphasis-start words
Eliminating seeds occurring in lower case more often than capitalized
Collecting labeled positives
Doing catalog lookups for 10 seeds:
Assessing catalog lookup results
Building primary rank dictionaries
Salvaging style eliminated seeds using lookup results
Doing catalog lookups for 0 catalog salvaged seeds:
Extending primary rank dictionaries
Salvaging style eliminated seeds using style of catalog salvaged seeds
Doing catalog lookups for 0 style salvaged seeds:
Extending primary rank dictionaries
Indexing epithet occurrences
Indexing labeled epithets and potential epithets
Indexing taxonomic status labels
Indexing potential authorities
Indexing name infixes and in-name symbols
Assembling taxonomic names
Expanding abbreviated genera and species
Linking taxonomic names with non-catalog genera to families
Linking taxonomic names to catalog data
Getting taxonomic names
Adding document authority for original names
Adding or resetting verbatim authorities
Bucketizing taxonomic names
Merging equal buckets
Merging compatible buckets
Handling new combinations and status changes
Transferring attributes already present in document
Sorting out done-with buckets
Loading authority data for 5 taxon names
Running Image Markup Tool 'Clean Table Annotations'
Running Image Markup Tool 'Remove Duplicate Annotations'
Running Image Markup Tool 'Mark Treatments (Headings Only)'
Wrapping document
Checking document
Loading document processor
Running Image Markup Tool 'Extract Materials Citations'
Wrapping document
Checking document
Loading document processor
Processing document
Error processing document 'D:\diglib\zootaxa\2017\temp\zootaxa.4299.4.8.pdf': Java heap space
java.lang.OutOfMemoryError: Java heap space
        at java.util.HashMap.newNode(Unknown Source)
        at java.util.HashMap.putVal(Unknown Source)
        at java.util.HashMap.put(Unknown Source)
        at java.util.HashSet.add(Unknown Source)
        at java.util.AbstractCollection.addAll(Unknown Source)
        at java.util.HashSet.<init>(Unknown Source)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler$DetailOverlay.<init>(MaterialsCitationHandler.java:3237)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler.extendMaterialsCitationDetailOverlay(MaterialsCitationHandler.java:3375)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler.extendMaterialsCitationDetailOverlay(MaterialsCitationHandler.java:3386)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler.extendMaterialsCitationDetailOverlay(MaterialsCitationHandler.java:3386)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler.extendMaterialsCitationDetailOverlay(MaterialsCitationHandler.java:3386)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler.extendMaterialsCitationDetailOverlay(MaterialsCitationHandler.java:3386)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler.extendMaterialsCitationDetailOverlay(MaterialsCitationHandler.java:3386)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler.extendMaterialsCitationDetailOverlay(MaterialsCitationHandler.java:3386)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler.extendMaterialsCitationDetailOverlay(MaterialsCitationHandler.java:3386)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler.extendMaterialsCitationDetailOverlay(MaterialsCitationHandler.java:3386)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler.extendMaterialsCitationDetailOverlay(MaterialsCitationHandler.java:3386)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler.extendMaterialsCitationDetailOverlay(MaterialsCitationHandler.java:3386)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler.extendMaterialsCitationDetailOverlay(MaterialsCitationHandler.java:3386)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler.extendMaterialsCitationDetailOverlay(MaterialsCitationHandler.java:3386)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler.extendMaterialsCitationDetailOverlay(MaterialsCitationHandler.java:3386)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler.extendMaterialsCitationDetailOverlay(MaterialsCitationHandler.java:3386)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler.extendMaterialsCitationDetailOverlay(MaterialsCitationHandler.java:3386)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler.extendMaterialsCitationDetailOverlay(MaterialsCitationHandler.java:3386)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler.extendMaterialsCitationDetailOverlay(MaterialsCitationHandler.java:3386)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler.extendMaterialsCitationDetailOverlay(MaterialsCitationHandler.java:3386)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler.extendMaterialsCitationDetailOverlay(MaterialsCitationHandler.java:3386)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler.extendMaterialsCitationDetailOverlay(MaterialsCitationHandler.java:3386)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler.extendMaterialsCitationDetailOverlay(MaterialsCitationHandler.java:3386)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler.extendMaterialsCitationDetailOverlay(MaterialsCitationHandler.java:3386)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler.createMaterialsCitationDetailOverlays(MaterialsCitationHandler.java:3283)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler.cleanMaterialsCitationDetails(MaterialsCitationHandler.java:3053)

D:\GoldenGateImagine_20170221>

**Comment by gsautter** [comment] 2017-08-09 06:27
Another one with the combinatorical explosion in the materials citation ... Still, this one's a duplicate of #177 and will resolve with the latter.

**Comment by myrmoteras** [comment] 2017-08-15 09:17
still does not work with version 20170815

Processing document 'D:\diglib\zootaxa\2017\temp1\zootaxa.4299.4.8.pdf'
 - loaded PDF of 4263317 bytes
Extracting page content
Assessing font char usage
Importing page words
Sanitizing page words and graphics
Handling flipped page content
Analyzing words in relation to figures and graphics
Storing custom fonts
Assessing number punctuation
Splitting page words
Generating page images
Generating pages
Analyzing page structure
Analyzing text stream structure
 - PDF converted, document ID is 'FFB65D5EFFEE7D258908FFF60501E67A'
 - assigned document style 'zootaxa.2013.journal_article'
Running Image Markup Tool 'Detect Document Structure'
Detecting document structure from 11 pages
 - gathering data
 - scoring page numbers:
 - checking page number sequence:
 - filling in missing page numbers:
 - detecting page headers
 - correcting empty tables
 - detecting tables
 - computing main text font size
 - detecting captions
 - detecting footnotes
 - indexing paragraph end words
 - de-hyphenating line breaks
 - merging interrupted paragraphs
 - identifying caption target areas
 - merging tables within pages
 - merging tables across pages
 - marking caption citations
 - marking headings and emphases
Running Image Markup Tool 'Add Document Meta Data'
Running Image Markup Tool 'Mark Taxonomic Keys'
Running Image Markup Tool 'Parse Bibliography'
Wrapping document
Checking document
Loading document processor
Running Image Markup Tool 'Mark Bibliographic Citations'
Wrapping document
Checking document
Loading document processor
Processing document
Running Image Markup Tool 'Mark Taxon Names'
Wrapping document
Checking document
Loading document processor
Collecting seed families and genera
Collecting above-genus seeds
Eliminating seeds from document head and bibliography
Eliminating stop words
Eliminating seeds with inappropriate suffixes
Eliminating document local stop words
Eliminating non-emphasis-start words
Eliminating seeds occurring in lower case more often than capitalized
Collecting labeled positives
Doing catalog lookups for 10 seeds:
Assessing catalog lookup results
Building primary rank dictionaries
Salvaging style eliminated seeds using lookup results
Doing catalog lookups for 0 catalog salvaged seeds:
Extending primary rank dictionaries
Salvaging style eliminated seeds using style of catalog salvaged seeds
Doing catalog lookups for 0 style salvaged seeds:
Extending primary rank dictionaries
Indexing epithet occurrences
Indexing labeled epithets and potential epithets
Indexing taxonomic status labels
Indexing potential authorities
Indexing name infixes and in-name symbols
Assembling taxonomic names
Expanding abbreviated genera and species
Linking taxonomic names with non-catalog genera to families
Linking taxonomic names to catalog data
Getting taxonomic names
Adding document authority for original names
Adding or resetting verbatim authorities
Bucketizing taxonomic names
Merging equal buckets
Merging compatible buckets
Handling new combinations and status changes
Transferring attributes already present in document
Sorting out done-with buckets
Loading authority data for 5 taxon names
Running Image Markup Tool 'Clean Table Annotations'
Running Image Markup Tool 'Remove Duplicate Annotations'
Running Image Markup Tool 'Mark Treatments (Headings Only)'
Wrapping document
Checking document
Loading document processor
Running Image Markup Tool 'Extract Materials Citations'
Wrapping document
Checking document
Loading document processor
Processing document
Error processing document 'D:\diglib\zootaxa\2017\temp1\zootaxa.4299.4.8.pdf': null
java.lang.NullPointerException
        at de.uka.ipd.idaho.gamta.AnnotationUtils.liesIn(AnnotationUtils.java:115)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler.classifyMaterialsCitationProperNames(MaterialsCitationHandler.java:4271)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler.markMaterialsCitations(MaterialsCitationHandler.java:2040)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler.process(MaterialsCitationHandler.java:544)
        at de.uka.ipd.idaho.goldenGate.plugin.analyzers.AnalyzerManager$MonitorableAnalyzerDocumentProcessor.process(AnalyzerManager.java:229)
        at de.uka.ipd.idaho.goldenGate.plugin.pipelines.PipelineManager$PipelineDocumentProcessor.process(PipelineManager.java:328)
        at de.uka.ipd.idaho.goldenGate.plugin.pipelines.PipelineManager$PipelineDocumentProcessor.process(PipelineManager.java:295)
        at de.uka.ipd.idaho.goldenGate.plugin.pipelines.PipelineManager$PipelineDocumentProcessor.process(PipelineManager.java:283)
        at de.uka.ipd.idaho.goldenGate.plugin.filteredProcessor.FilteredDocumentProcessorManager$FilteredDocumentProcessor.process(FilteredDocumentProcessorManager.java:152)
        at de.uka.ipd.idaho.im.imagine.plugins.tools.ImageMarkupToolManager$DpImageMarkupTool.process(ImageMarkupToolManager.java:547)
        at de.uka.ipd.idaho.im.imagine.batch.GoldenGateImagineBatch.main(GoldenGateImagineBatch.java:430)

**Comment by gsautter** [comment] 2017-08-15 11:01
In such cases, starting over should help now, at least if you specify a few more arguments. `CACHE=./<myCache>`, for instance, will direct caching at a specific folder. Also, the latest version of the batch caches processing results after each step, so you don't have to do all the PDF decoding again if the taxonomic names fail, or have to do the latter again if the materials citations fail.
Interestingly, I don't see any of the saving log messages in your post, though ... maybe it's simply that you didn't specify the `CACHE=` parameter. There's a whole bunch of new parameters that all help reduce effort. Just start the batch without specifying a PDF, and it prints them all. Here a list of the ones useful for influencing processing behavior and resource consumption anyway:
- `CACHE`: the root folder for all data caching folders (I use `CACHE=./BatchCache`)
- `DT`: the type of the PDF files to process (I use `DT=D` for born-digital where applicable)
- `FM`: the way of handling embedded fonts (relevant only for born-digital, I often use `FM=U` upfront to only really decode characters that come without a Unicode mapping)`
- `CS`: the char set for decoding embedded fonts (relevant only when decoding fonts, I often use `CS=S` for full Latin plus scientific symbols)`
- `ST` no value, just add this token to the comand to make the batch run on a single core (helps reduce memory and CPU consumption at cost of increased processing time)

**Comment by gsautter** [comment] 2017-08-15 11:11
What I see in this one is an enumeration of 9 specimen codes, each of which have a collection code embedded in them, resulting in 2^9=512 alternatives for that part alone. Small wonder with takes a while.

This is a combinatorical explosion as well, just like the cases before, only one of a different sort (actual materials citation data), and thus will require a different solution. Working on it.

**Comment by gsautter** [comment] 2017-08-15 23:26
This one should be fixed now as well with the latest build I just put up on http://tb.plazi.org/GgServer/Downloads/GgImagine-Default.imagine.zip ...

I guess combinatorical explosions will just keep on happening every once in a while as a new and even more pathological case comes up. They are kind of inherent to the materials citation detail detection and classification technique we're using, but on the other hand that technique is pretty much without competition in the accuracy department. All I can do is keep on refining its filters as we encounter said cases, cases we most likely couldn't even think of when trying to think up potential problems.

**Closed by gsautter** 2017-08-15 23:26 UTC
