### ISSUE TITLE
article with phantom treatments

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#62] opened 2017-02-06 20:37 UTC
@gsautter  this is a very strange EJT article, that we can't fix, nor do we understand why the figurecitations are not linked in TB

![image](https://cloud.githubusercontent.com/assets/4609956/22665085/c1cd50c4-ecb3-11e6-8bf3-3255ef13c9c1.png)

the file name is 346-1786-1-PB. However this file has originally been uploaded as Bosselaers, J., _ Van Keer, J. (2016). A redescription of Harpactea dufouri (Thorell, 1873)(Araneae, Dysderidae), its occurrence outside the Balearic Islands, and some notes on 

and this later name is still maintained in the metadat of the the treatment that is in TB. 

https://zenodo.org/record/269002#.WJja_xorK0o
that cites this treatment http://treatment.plazi.org/id/884C36210264FFF5FDAE5F8F2D76FD19 

Also, in the dashboards Jeremey prepared, this document seems not to have a treatment included.

How can we fix this file?
I have no tricks available anymore....

thanks for looking into this

donat

**Comment by gsautter** [comment] 2017-02-06 20:40
OK, I'll go hunting this one instead of fixing whatever I figured out for #57 ...

**Comment by gsautter** [comment] 2017-02-06 20:55
This one is not on Zenodo at all ... look at http://treatment.plazi.org/GgServer/xml/884C36210264FFF5FDAE5F8F2D76FD19 , there is no `ID-Zenodo-Dep` attribute. Keep in mind that you have to release the document (close it in GGI) for the Zenodo uploader to be able to take over. The uploader needs to be able to acquire the lock so it can write back the DOIs and HTTP URIs it gets from Zenodo in response to the upload.

However, in this instance, the problem is a different one: The document was uploaded to the XML Article Repo before (by Jeremy) via "Export -> Export Document to GoldenGATE Server", so the update cannot be forwarded from the IMF Repo to the XML based parts of TB, as the XML already exists.

**Comment by gsautter** [comment] 2017-02-06 20:56
To bad I just had to go hunting figures again, was really looking forward to fixing #57 ...

**Comment by myrmoteras** [comment] 2017-02-06 21:00
yes, it is in Zenodo

https://zenodo.org/record/269002#.WJjjbhorK0p

and here the figures https://doi.org/10.5281/zenodo.269003 
https://doi.org/10.5281/zenodo.269004

**Comment by myrmoteras** [comment] 2017-02-06 21:02
and the document name is this 346-1786-1-PB , last upload 2017-02-06 21:37:52

**Comment by gsautter** [comment] 2017-02-06 21:09
Sure it's in Zenodo ... it's only that the Zenodo linkup attributes (`ID-Zenodo-Dep` of document and DOIs / HTTP URIs of figures) cannot be forwarded to the XML Article Repo or XML Treatment Repo because the document already exists there from Jeremy's earlier XML based upload ... the IMF Repo ==> XML Article Repo transfer does not overwrite an XML document it has not created itself, plainly to prevent data loss due to overwriting.

**Comment by myrmoteras** [comment] 2017-02-06 21:16
how to fix it? the former upload has a very long document name that makes it very difficult to impossible to write scripts to get the dashboard. So Jeremy renamed and uploaded it. This had also a problem with the treatment, because the subsubsection type"nomenclature" has been missing, that is fixed in the other later filed.

**Comment by gsautter** [comment] 2017-02-06 21:19
You can open GGE, use "File -> Load Document from GoldenGATE Server" to get the document list, find the document, and delete it. After that, you can open the IMF in GGI (also from the server), make some mini change, and then save and close it again. Instead, you can also just tell me you did the deletion, and I'll manually trigger the IMF Strore ==> XML Article Repo forward.

**Comment by myrmoteras** [comment] 2017-02-06 21:21
ok - but which is the file name of the first file? I wanted to do this, but can't find the file.

**Comment by gsautter** [comment] 2017-02-06 21:26
Look at http://treatment.plazi.org/id/884C36210264FFF5FDAE5F8F2D76FD19 ... "treatment provided by Jeremy (2017-02-06 12:14:22)" should give you all you need to use the filters. If not, the document name is visible in the `docName` attribute in  http://treatment.plazi.org/GgServer/xml/884C36210264FFF5FDAE5F8F2D76FD19

**Comment by myrmoteras** [comment] 2017-02-06 21:35
I don't find it. There is no such file. Does this mean, that Jeremy has it open?
![image](https://cloud.githubusercontent.com/assets/4609956/22667314/8fa5f1f6-ecbc-11e6-8203-69558ec6168b.png)

**Comment by gsautter** [comment] 2017-02-06 21:40
Try "Uloaded by - jeremy" and "Uploaded - less than - one week ago" ... but it's true, you cannot see the document if Jeremy still holds the lock.

**Comment by myrmoteras** [comment] 2017-02-06 22:02
ok - you actually don't know whether it is there.

**Comment by gsautter** [comment] 2017-02-06 22:07
It is there, and Jeremy does _not_ hold the lock ... I meant "Open Document from GG Server" in GGE (E for Editor), not GGI.

In GGI, you see the the contents of IMF store. If you want to look at the XML Article Repo, you have to use GGE.

**Comment by myrmoteras** [comment] 2017-02-06 22:27
I never heard anything from GGE. Where is it?

Get Outlook for Android<https://aka.ms/ghei36>


________________________________

**Comment by gsautter** [comment] 2017-02-06 22:51
You never knew GoldenGATE Editor, right? The good old piB Configuration, etc. ...

**Comment by myrmoteras** [comment] 2017-02-07 06:11
I did not know that I can open IMF files with PiB.  Or did we at produce boxex using piB? 

![image](https://cloud.githubusercontent.com/assets/4609956/22679719/7d2f743c-ed04-11e6-8c70-b0a2411c8463.png)

http://treatment.plazi.org/GgServer/xml/884C36210264FFF5FDAE5F8F2D76FD19

also, load file from server does not work in PiB

**Comment by gsautter** [comment] 2017-02-07 19:50
I did not mean you should _open_ an IMF with piB ... just open the "Load from GG Server" dialog to the the document _list_ from DIO (aka XML Article Repo), find Jeremy's prematurely uploaded document, and delete it via a right click and "Delete". All of that to make way for re-uploading the IMF through IMF store and then all the way through to TB after the old XML is out of the way.

**Comment by gsautter** [comment] 2017-02-07 19:51
Nevermind, though, I've created a "force overwrite" admin action and will use it.

**Closed by gsautter** 2017-02-07 19:51 UTC
