### ISSUE TITLE
file does not batch process: MC issue zootaxa.4643.1.1.

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#718] opened 2019-07-22 07:12 UTC
[GgImagineBatch.20190722-0826.out.zip](https://github.com/gsautter/goldengate-imagine/files/3416087/GgImagineBatch.20190722-0826.out.zip)

zootaxa.4643.1.1.pdf is here https://drive.google.com/open?id=0B_yrQwn4yBySTlBxMnhWd3o1Zkk

**Comment by gsautter** [comment] 2019-09-01 23:26
Closing as duplicate of #755 ...

**Closed by gsautter** 2019-09-01 23:26 UTC
