### ISSUE TITLE
pdf not processed  zootaxa.4299.3.3.

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#188] opened 2017-08-09 04:58 UTC
[zootaxa.4299.3.3.pdf](https://github.com/gsautter/goldengate-imagine/files/1210366/zootaxa.4299.3.3.pdf)
 - detecting page headers
 - correcting empty tables
 - detecting tables
 - computing main text font size
 - detecting captions
 - detecting footnotes
 - indexing paragraph end words
 - de-hyphenating line breaks
 - merging interrupted paragraphs
 - identifying caption target areas
 - merging tables within pages
 - merging tables across pages
 - marking caption citations
 - marking headings and emphases
Running Image Markup Tool 'Add Document Meta Data'
Running Image Markup Tool 'Mark Taxonomic Keys'
Running Image Markup Tool 'Parse Bibliography'
Wrapping document
Checking document
Loading document processor
Running Image Markup Tool 'Mark Bibliographic Citations'
Wrapping document
Checking document
Loading document processor
Processing document
Running Image Markup Tool 'Mark Taxon Names'
Wrapping document
Checking document
Loading document processor
Collecting seed families and genera
Collecting above-genus seeds
Eliminating seeds from document head and bibliography
Eliminating stop words
Eliminating seeds with inappropriate suffixes
Eliminating document local stop words
Eliminating non-emphasis-start words
Eliminating seeds occurring in lower case more often than capitalized
Collecting labeled positives
Doing catalog lookups for 21 seeds:
Assessing catalog lookup results
Building primary rank dictionaries
Salvaging style eliminated seeds using lookup results
Doing catalog lookups for 0 catalog salvaged seeds:
Extending primary rank dictionaries
Salvaging style eliminated seeds using style of catalog salvaged seeds
Doing catalog lookups for 0 style salvaged seeds:
Extending primary rank dictionaries
Indexing epithet occurrences
Indexing labeled epithets and potential epithets
Indexing taxonomic status labels
Indexing potential authorities
Indexing name infixes and in-name symbols
Assembling taxonomic names
Expanding abbreviated genera and species
Linking taxonomic names with non-catalog genera to families
Linking taxonomic names to catalog data
Getting taxonomic names
Adding document authority for original names
Adding or resetting verbatim authorities
Bucketizing taxonomic names
Merging equal buckets
Merging compatible buckets
Handling new combinations and status changes
Transferring attributes already present in document
Sorting out done-with buckets
Loading authority data for 7 taxon names
Running Image Markup Tool 'Clean Table Annotations'
Running Image Markup Tool 'Remove Duplicate Annotations'
Running Image Markup Tool 'Mark Treatments (Headings Only)'
Wrapping document
Checking document
Loading document processor
Running Image Markup Tool 'Extract Materials Citations'
Wrapping document
Checking document
Loading document processor
Processing document
Error processing document 'D:\diglib\zootaxa\2017\temp\zootaxa.4299.3.3.pdf': GC overhead limit exceeded
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.HashMap.newNode(Unknown Source)
        at java.util.HashMap.putVal(Unknown Source)
        at java.util.HashMap.put(Unknown Source)
        at java.util.HashSet.add(Unknown Source)
        at java.util.AbstractCollection.addAll(Unknown Source)
        at java.util.HashSet.<init>(Unknown Source)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler$DetailOverlay.<init>(MaterialsCitationHandler.java:3237)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler.extendMaterialsCitationDetailOverlay(MaterialsCitationHandler.java:3375)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler.extendMaterialsCitationDetailOverlay(MaterialsCitationHandler.java:3386)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler.extendMaterialsCitationDetailOverlay(MaterialsCitationHandler.java:3386)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler.extendMaterialsCitationDetailOverlay(MaterialsCitationHandler.java:3386)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler.extendMaterialsCitationDetailOverlay(MaterialsCitationHandler.java:3386)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler.extendMaterialsCitationDetailOverlay(MaterialsCitationHandler.java:3386)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler.extendMaterialsCitationDetailOverlay(MaterialsCitationHandler.java:3386)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler.extendMaterialsCitationDetailOverlay(MaterialsCitationHandler.java:3386)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler.extendMaterialsCitationDetailOverlay(MaterialsCitationHandler.java:3386)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler.extendMaterialsCitationDetailOverlay(MaterialsCitationHandler.java:3386)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler.extendMaterialsCitationDetailOverlay(MaterialsCitationHandler.java:3386)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler.extendMaterialsCitationDetailOverlay(MaterialsCitationHandler.java:3386)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler.extendMaterialsCitationDetailOverlay(MaterialsCitationHandler.java:3386)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler.extendMaterialsCitationDetailOverlay(MaterialsCitationHandler.java:3386)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler.extendMaterialsCitationDetailOverlay(MaterialsCitationHandler.java:3386)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler.extendMaterialsCitationDetailOverlay(MaterialsCitationHandler.java:3386)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler.extendMaterialsCitationDetailOverlay(MaterialsCitationHandler.java:3386)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler.extendMaterialsCitationDetailOverlay(MaterialsCitationHandler.java:3386)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler.extendMaterialsCitationDetailOverlay(MaterialsCitationHandler.java:3386)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler.extendMaterialsCitationDetailOverlay(MaterialsCitationHandler.java:3386)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler.extendMaterialsCitationDetailOverlay(MaterialsCitationHandler.java:3386)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler.extendMaterialsCitationDetailOverlay(MaterialsCitationHandler.java:3386)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler.extendMaterialsCitationDetailOverlay(MaterialsCitationHandler.java:3386)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler.extendMaterialsCitationDetailOverlay(MaterialsCitationHandler.java:3386)
        at de.uka.ipd.idaho.plugin.materialsCitations.MaterialsCitationHandler.extendMaterialsCitationDetailOverlay(MaterialsCitationHandler.java:3386)

**Comment by gsautter** [comment] 2017-08-09 06:26
Another one with the combinatorical explosion in the materials citation ... got it, we have a serious one there. And I've been working on it every single minute I could muster since Sunday night. Still, this one's a duplicate of #177 and will resolve with the latter.

**Closed by gsautter** 2017-08-09 06:26 UTC
