### ISSUE TITLE
pdf not processing: zootaxa.4296.1.1

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#183] opened 2017-08-08 11:41 UTC
this is a large file, that I can't include here. The link to the file is here http://www.mapress.com.libraryproxy.amnh.org:9000/j/zt/article/download/zootaxa.4296.1.1/11858

https://drive.google.com/a/plazi.org/file/d/0B_yrQwn4yBySTDFOUUJzdVVmclE/view?usp=sharing

Processing document 'D:\diglib\zootaxa\2017\temp\zootaxa.4296.1.1.pdf'
 - loaded PDF of 42051864 bytes
Extracting page content
Error processing document 'D:\diglib\zootaxa\2017\temp\zootaxa.4296.1.1.pdf': null
java.lang.NullPointerException
        at de.uka.ipd.idaho.im.pdf.PdfExtractor.getPdfPageData(PdfExtractor.java:616)
        at de.uka.ipd.idaho.im.pdf.PdfExtractor.loadTextPdf(PdfExtractor.java:1332)
        at de.uka.ipd.idaho.im.pdf.PdfExtractor.loadTextPdf(PdfExtractor.java:1177)
        at de.uka.ipd.idaho.im.imagine.batch.GoldenGateImagineBatch.main(GoldenGateImagineBatch.java:411)

**Comment by gsautter** [comment] 2017-08-08 19:12
This one also looks like a duplicate of #181 to me ... same error in same position. Odds are this will be closed with #181.

**Closed by gsautter** 2017-08-08 19:12 UTC

**Comment by gsautter** [comment] 2017-08-14 04:29
For some reason this file won't even download from Google Drive ... keeps breaks up around 41 MB. How large is it in total?

**Comment by myrmoteras** [comment] 2017-08-14 04:33
45 MB

**Comment by myrmoteras** [comment] 2017-08-14 04:40
Try this link
https://drive.google.com/a/plazi.org/file/d/0B_yrQwn4yBySQi1XZGVjRnA1Qnc/view?usp=sharing

and let me know

**Comment by gsautter** [comment] 2017-08-14 17:38
This one worked nicely, now I can test.

**Comment by gsautter** [comment] 2017-08-14 17:43
Running into a few memory problems on this one during font decoding, but it runs just fine way beyond the point of the exception in the original ticket. I just cannot seem to reproduce this error, and, looking at the code, don't see just why it would happen if not for some _really_ weird circumstances.
