### ISSUE TITLE
Text stream issue

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#5] opened 2016-12-01 11:01 UTC
@gsautter in this example,
* many of the taxonomic names have not been discovered. 
* the text stream is wrong. the "." is not the successor from "V" and the predecessor of the species name.
* the name cannot be marked up properly

![image](https://cloud.githubusercontent.com/assets/4609956/20791497/9fc0da80-b7bd-11e6-8f6a-6bda41486adc.png)

[Ghielmi_et_al-2016-Journal_of_Zoological_Systematics_and_Evolutionary_Research.pdf](https://github.com/gsautter/goldengate-imagine/files/624321/Ghielmi_et_al-2016-Journal_of_Zoological_Systematics_and_Evolutionary_Research.pdf)

http://tb.plazi.org/GgServer/summary/C06DF312FF8F6B08FFEDFFE3FFFCFF8E

**Comment by gsautter** [comment] 2016-12-05 23:25
Note that the "V" has a darker frame than the other words around it. That means it has a different text stream type, and also belongs to a different text stream.

To repair such cases:
- Make sure text streams are showing
- Drag a box around the whole paragraph
- Use "Order Text Stream" to make the paragraph consist of a single text stream again.

I'll investigate why the "V"s were cut out in the first place ...

**Comment by gsautter** [comment] 2016-12-05 23:45
Decoded this PDF several times now, with different font decoder options. I cannot seem to reproduce the "V"s being cut out, or mis-decoded, or anything that would prevent them from being integrated in the text stream they belong to.

The failure to recognize taxon names is a downstream error caused by the genus abbreviation being excluded from text flow.

**Comment by gsautter** [comment] 2016-12-05 23:51
I close this one for inability to reproduce the error. As this is a font issue, it might be machine dependent, as the built-in comparison fonts tend to render slightly differently on different platforms.

If it keeps occurring on your machine, try loading the PDF with "PDF Documents (born-digital, render embedded fonts, but do not decode glyphs)".
That option relies upon the PDF fonts to be friendly, which they in fact are in most cases, and does not attempt to break any scrambled fonts. On top of being way faster than the full decoding approach, this also prevents the occasional mis-decoding. And if the fonts do come up scrambled, you can still re-open the PDF with the full font decoding enabled.

**Closed by gsautter** 2016-12-05 23:51 UTC
