### ISSUE TITLE
materialsCitation: false positive

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#561] opened 2019-01-11 12:03 UTC
![image](https://user-images.githubusercontent.com/4609956/51032689-3be08a80-15a1-11e9-8d54-3927a22cc6a8.png)

in this case the MC has not been detected, but the following paragraph as false positive
http://tb.plazi.org/GgServer/summary/0767FFD8082E3F06FFB13B380732F137

**Comment by myrmoteras** [comment] 2019-01-11 12:06
![image](https://user-images.githubusercontent.com/4609956/51032807-a1cd1200-15a1-11e9-9302-5e189367f5dd.png)

**Comment by gsautter** [comment] 2019-01-16 15:23
I think this is a duplicate of #557 ... will handle the materials citations as a whole there.

**Closed by gsautter** 2019-01-16 15:23 UTC
