### ISSUE TITLE
did not process: zootaxa.4453.1.1

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#506] opened 2018-10-03 15:08 UTC
file is too big. it is in this folder

https://drive.google.com/drive/folders/1zuD8LbnBy4uixmNgBslkCENXOtfW0bP3?usp=sharing

**Comment by gsautter** [comment] 2018-10-03 19:28
I guess it this is a duplicate of #501 ... will report on my findings in the latter.

**Closed by gsautter** 2018-10-03 19:28 UTC
