### ISSUE TITLE
caption image link,upload to BLR  does not work; 

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#212] opened 2017-08-26 09:28 UTC
this file quartReviewBiology693564.pdf loaded to TB does not load to BLR probably because the link between figure 1 and image is not made

quartReviewBiology693564.pdf

https://user-images.githubusercontent.com/4609956/29740052-fa711cc0-8a4d-11e7-9fe9-63ce57de8206.png

I can't fix it.

**Comment by gsautter** [comment] 2017-08-26 15:10
Is this the same document as in #211?

**Comment by gsautter** [comment] 2017-08-26 15:54
If you mark the caption as such, you would be able to link it to the image, and to figure citations as well ... The main reason the caption wasn't detected most likely is the mingled word-to-font linking (see #211) and the resulting case problems (the caption start with "FIGuRE" ...).

The caption comping in two paragraphs might also cause a problem for automated detection, but that could likely be overcome with a conditional lifting of the restriction of captions to one paragraph (which is intended to prevent false positives in automated detection, and does that quite well), controlled by a respective switch in a document style template.

**Comment by gsautter** [comment] 2017-08-26 16:34
The image is uploaded now (https://zenodo.org/record/849557), but I cannot seem to find the PDF ... for what I see in the server log, publishing the PDF deposition fails for some reason.

**Comment by gsautter** [comment] 2017-08-26 16:43
Closing this one for now, as the problem is solved, and I'll work on the fonts under #211.

The style template switch for two-paragraph captions will only start to matter if we choose to take a go at this journal, and we'll come back to it then.

**Comment by gsautter** [comment] 2017-08-26 16:44
Found the PDF as well ... was no PDF attached for some reason, so it did not publish. Uploaded it now.

**Closed by gsautter** 2017-08-26 16:43 UTC
