### ISSUE TITLE
table not properly recognized / editing zootaxa.4291.1.1

### ISSUE THREAD

**Issue by myrmoteras** [gsautter/goldengate-imagine#283] opened 2017-10-16 13:56 UTC
This is a rotated table spanning over multiple pages. It has either rows of one or two lines, most of them are not properly recognized.

I also don't know how to merge to rows.

The table only worked once I imported the article with latin, not with glyphs

![image](https://user-images.githubusercontent.com/4609956/31598462-1d8bb292-b24e-11e7-8bb5-4bbcb57538da.png)

**Comment by gsautter** [comment] 2017-10-16 19:12
Well, yes ... that's because with an unfriendly font, glyphs alone just won't cut it ... Latin does the same as glyphs (render the characters), but on top of that "visually" compares the rendering results to all Latin characters to figure out what the glyphs really are (to the eyes of a human reader). That's the only way of dealing with unfriendly fonts, i.e., ones that come without a faithful Unicode mapping.

The reason to start out with Glyphs alone is that aforementioned "visual" comparison takes a good bit of computation time, and that time you can spare by skipping over it, which works perfectly fine with friendly fonts.
If you know the latter case is likely, Glyphs is just faster, but if you know the latter case is unlikely, Latin is the way to go.

**Comment by gsautter** [comment] 2017-10-16 21:27
I could reproduce the problem ... the font in this table is really unfriendly. Even with Latin decoding, it loses the "o" for some reason ... Investigating how that happens right now.

**Comment by gsautter** [comment] 2017-10-16 23:40
Found out that problem font contains _two_ identical "o" glyphs ... so one gets excluded on the assumption of non-ambiguity of character representation. The latter usually works very well when it comes to getting several somewhat similar glyphs assigned to the right characters, which is why the decoder uses it. In this very case, however, it looks like it's getting in the way a bit ... will try and figure out a way of handling this.

**Comment by gsautter** [comment] 2017-10-24 23:20
Resolved, new build to come.

This is a very odd case, as the two "o"s causing the problem even _render_ with identical sequences of vector graphics commands ... meaning to say they are _exactly_ the same. Left to wonder how they both end up in a single font together ... sloppiness being the most likely option, maliciousness at least a possible one. Anyway, solved now. Another category of embedded font decoding booby trap disabled.

**Closed by gsautter** 2017-10-24 23:20 UTC
